### ISSUE TITLE
peercoin client doesn't use getrawtransaction .

### ISSUE THREAD

**Issue by mark-bl** [FuzzyBearBTC/PeercoinBlockExplorer#11]
Because peercoin client doesn't use getrawtransaction , we have two options
1)implement it in the code of the block explorer.
2)implement it inside the client ( this is a better solution ).

It might be better to wait for SunnyKing and the new client ( it might have getrawtransaction and then we wouldn't have to write ugly hacks )..

**Comment by FuzzyBearBTC** [comment]
sunny king will release the code for testnet release soon.. we should look to
see if it is in there.. or i can ask him about it??? If it is not... I would say
yes we should include it in the main client.. even if it only on my Fuzzybear
branch for now or something.. but see if you can find the code in bitcoin that
we would need to include in the peercoin client and I can see if I can include
myself if you point me in the right direction :)

Fuzzybear

**Comment by mark-bl** [comment]
the code in the bitcoin client is at : https://github.com/bitcoin/bitcoin/blob/master/src/rpcrawtransaction.cpp#L113

I say lets wait for the sunny king to release the code, and then we'll look into this issue again.

Mark.

**Comment by FuzzyBearBTC** [comment]
sample code for PPC getrawtransaction https://github.com/kactech/ppcoin/commit/ad2a74b0795704c7da405e6a2be331b7e31db111

**Comment by sapph1re** [comment]
Looks like the getrawtransaction issue is still unresolved. There is nothing about it in the 0.4.0 ppcoin code.
http://ppc.cryptocoinexplorer.com/ has all the transactions info and txid lookup. Does anybody know how they implemented it? Maybe they have a version of ppcoin with getrawtransaction?

Did you ask SunnyKing about the issue, @FuzzyBearBTC?

Btw, the last link (sample code) doesn't work, 404.

**Comment by dlio** [comment]
Does anyone have an update on the status of getrawtransaction or a workaround in the meantime?  There must be a great number of projects from which peercoin is being excluded due to this omission.  FuzzyBear -- could you please update your 404 link to sample code in the kactech/ppcoin repo or put it in a gist?

**Comment by FuzzyBearBTC** [comment]
getrawtransaction now in the daemon client
