### ISSUE TITLE
RPC Down?

### ISSUE THREAD

**Issue by danbartram** [FuzzyBearBTC/PeercoinBlockExplorer#14]
The `node_info` div contents is empty, the RPC server seems to not be supplying the data.

Trying to view block information also returns empty data sets.

Is the RPC server down?

**Comment by FuzzyBearBTC** [comment]
hmm no i can make getinfo calls from cmd window... checking the credentials

**Comment by FuzzyBearBTC** [comment]
https://github.com/FuzzyBearBTC/PeercoinBlockExplorer/blob/master/src/bc_daemon.php#L8
Be sure to use values that match the ppcoin.conf running on the server!

**Comment by danbartram** [comment]
Sorry for the confusion - I meant on the official site - http://blockexplorer.peercointalk.org/

It's working now though, thanks.

**Comment by FuzzyBearBTC** [comment]
No worries this serves as a reminder for future devs looking to fork and a prompter in debugging for me :)
