### ISSUE TITLE
Re-design?

### ISSUE THREAD

**Issue by danbartram** [FuzzyBearBTC/PeercoinBlockExplorer#7]
I had a go at re-designing the landing page to look a bit cleaner, and wondered if you'd be interested in me submitting it as a pull request?

Also any suggestions/requests before I submit the pull?

![Imgur Screenshot of Redesign](http://i.imgur.com/y5bYn4D.png)

**Comment by FuzzyBearBTC** [comment]
Yup I like it, except the header... drop the original image back in i would
say.. or feel free to try some other designs.. wanted some kind of logo really
for the BE

really like the block count green and links green etc :) nice work btw :)

Fuzzybear

**Comment by danbartram** [comment]
Alright, cool, I'll have a play with the header and logo and see what I can come up with.

Do you want me to just restore the logo image and submit a pull so that you can tweak it, or wait until it's all done?

Thank you ;)

**Comment by FuzzyBearBTC** [comment]
What ever is easy for you... I think it would be nice to see it with the current
logo and usually someone comes along and comp[lains I don't do Photoshop right
:P and makes me a better image.. so drop it back in and then submit a new pull
request if you have a better image at a later date.  Might as well get the tips
for the commits you have done today :D

Really nice to have someone work on this with me and look over the code so a
personal thank you for this :)

Fuzzybear

**Comment by danbartram** [comment]
I love your passion with this. You're welcome, I'm glad to be of help.

**Comment by danbartram** [comment]
I added the old header image back in for you and submitted a new pull request #8, see if you like it better.
